### ISSUE TITLE
Improve voting UX a bit

### ISSUE THREAD

**Issue by folkyatina** [lidofinance/scripts#23]
There is a [line](https://github.com/lidofinance/scripts/blob/ebf4dc0b006f881d9e0a4488051a40472efc37d5/utils/voting.py#L63) "Does it look good?". 
Adding variants "y/n" may be helpful 

Also, there is a huge pause after confirming and it make you nervous. If it print something like "Voting confirmed. Wait a moment, please". It can be reassuring.

**Comment by kadmil** [comment]
I guess you may just go ahead and do pr with those — would be happy to review & accept

**Comment by TheDZhon** [comment]
The fix is here right now, nvm.
It is going to be merged after the next vote happens.
