### ISSUE TITLE
There is a broken parsing of NodeOperatorAdded events in tests

### ISSUE THREAD

**Issue by folkyatina** [lidofinance/scripts#24]
So node validation does not work [here](https://github.com/lidofinance/scripts/blob/ebf4dc0b006f881d9e0a4488051a40472efc37d5/tests/test_2022_01_13.py#L164)

**Comment by TheDZhon** [comment]
I've finally found a reason behind it.
Going to fix it till the next vote is announced.

**Comment by TheDZhon** [comment]
Just for the record. The behavior is reproduced with `string` function parameters while using solidity 0.4.x compiler with the `external` visibility functions.

For example:

```solidity
pragma solidity ^0.4;

contract Sample {
    event SampleEvent(
        string name
    );

    function fireSampleEventExternal(string _name) external {
        emit SampleEvent(_name); //BROKEN
    }

    function fireSampleEventPublic(string _name) public {
        emit SampleEvent(_name); //WORKS
    }
}
```
