### ISSUE TITLE
Add ETHERSCAN_TOKEN secret

### ISSUE THREAD

**Issue by arwer13** [lidofinance/scripts#71]
Due to the Etherscan API limit:

[example run](https://github.com/lidofinance/scripts/runs/6772017666?check_suite_focus=true)

> BrownieEnvironmentWarning: No etherscan API token set. You may experience issues with rate limiting. Visit https://etherscan.io/register to obtain a token, and then store it as the environment variable $ETHERSCAN_TOKEN

> ValueError: Failed to retrieve data from API: {'status': '0', 'message': 'NOTOK', 'result': 'Max rate limit reached, please use API Key for higher rate limit'}

**Comment by TheDZhon** [comment]
I see that we have 
```ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}```
for our [CI workflow](https://github.com/lidofinance/scripts/blob/master/.github/workflows/test.yml#L79) setup 

CC: @n0guest, @dgusakov, could you please confirm that setup is correct?

**Comment by n0guest** [comment]
Sorry, my bad (mistype in secret's name). Just fixed, plz, try again

**Comment by TheDZhon** [comment]
Resolved by @n0guest 

![image](https://user-images.githubusercontent.com/961317/172805226-50e956b3-2315-4b0f-a031-acd7e3ae6359.png)
